# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-162829284-4'


# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'envelope', link: 'mailto:imsa@ntu.im', text: '歡迎寄信給我們'}
- {icon: 'facebook', link: 'https://www.facebook.com/Climas-臺大-中文x資管x大氣-聯合迎新宿營-103525468044636/', text: '查看粉絲專頁'}


# Customize site text
title: "CLIMAS | 資管中文大氣聯合宿營"
header: "CLIMAS"